require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - database_validations/rubocop/cops

inherit_gem:
  test-prof: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
